### PR TITLE
Adding 'unsign_payload' parameters

### PR DESCRIPTION
**Pull request by tbass134**
adding new property called ‘unsign_payload’ that when set, allows the x-amz-content-sha256 to be set to UNSIGNED_PAYLOAD

this is necessary for using the unsigned payload option in Signature Calculations for the Authorization Header when sending the payload in a single chunk. 

Certain applications, like S3 and Lex have this option. 
On Lex services, this option MUST be set.
See http://docs.aws.amazon.com/lex/latest/dg/gl-guidelines.html
for more information

### CODE REVIEW

**Comment by martyndavies** [comment]
Any update on whether this can be merged to master @sam-washington ?

**Comment by tbass134** [comment]
@martyndavies i think this repo is no longer maintained.

**Comment by tbass134** [comment]
@tedder can this PR be looked at?

**Comment by tedder** [comment]
Sure- can you rebase and give some examples of usage? (eg a code snippet)

**Comment by tedder** [comment]
closing, if this is wanted please update and give a test.

**Pull request closed without merging**
