### PR TITLE
Fixes #66 - add MANIFEST.in to include HISTORY.md in package

### LINKED ISSUE #66: pip install from .tar.gz broken - HISTORY.md not packaged
`setup.py` reads in `HISTORY.md`, but that file is not present in the `1.2.2 source tarball distribution on PyPI. As a result, installing from source/tarball fails.

This can be verified by trying to install the .tar.gz currently on PyPI, or just looking at it and confirming that HISTORY.md is not included. It looks to me like this needs a [MANIFEST.in](https://packaging.python.org/en/latest/guides/using-manifest-in/) file.

```
jantman@phoenix:pts/8:~/tmp$ python --version
Python 3.10.9
jantman@phoenix:pts/8:~/tmp$ pip --version
pip 22.3.1 from /usr/lib/python3.10/site-packages/pip (python 3.10)
jantman@phoenix:pts/8:~/tmp$ pip install requests-aws4auth -t lambda-deps/ --no-binary :all:
DEPRECATION: --no-binary currently disables reading from the cache of locally built wheels. In the future --no-binary will not influence the wheel cache. pip 23.1 will enforce this behaviour change. A possible replacement is to use the --no-cache-dir option. You can use the flag --use-feature=no-binary-enable-wheel-cache to test the upcoming behaviour. Discussion can be found at https://github.com/pypa/pip/issues/11453
Collecting requests-aws4auth
  Using cached requests-aws4auth-1.2.2.tar.gz (25 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-nju4w6mc/requests-aws4auth_1127f02618df432787af867797df289a/setup.py", line 27, in <module>
          with codecs.open('HISTORY.md', 'r', 'utf-8') as f:
        File "/usr/lib/python3.10/codecs.py", line 906, in open
          file = builtins.open(filename, mode, buffering)
      FileNotFoundError: [Errno 2] No such file or directory: 'HISTORY.md'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

### PR DESCRIPTION
**Pull request by jantman**
This PR adds a MANIFEST.in that includes HISTORY.md, in order to fix #66.

This can be verified by trying to install the built source tarball, which now works.

### CODE REVIEW

**Comment by vinitkumar** [comment]
Please merge this @tedder ?

**Comment by tedder** [comment]
@jantman thanks for the nudge.

**Review by tedder — APPROVED** [review]

**Comment by vinitkumar** [comment]
It would be awesome if you could do a release to PyPI as well, because that build is broken. Thank you for merging this PR.

**Comment by tedder** [comment]
working on that build, yeah.

**Comment by tedder** [comment]
🪄
https://pypi.org/project/requests-aws4auth/1.2.3/

**Comment by vinitkumar** [comment]
You are wonderful. Thanks for your quick effort.

**Pull request merged**
