### PR TITLE
factorize constants in class header

### PR DESCRIPTION
**Pull request by tardyp**
This allows this module to be used to support authentication derived from aws4

hyper.sh is one of those:
https://github.com/hyperhq/hypercli/blob/master/vendor/src/github.com/docker/engine-api/client/sign4.go

This will allow to remove a copy of aws4auth in hyper-compose
https://github.com/tardyp/hyper-compose/commit/e4244a01330af4076fa78133495cbaa85182855a

### CODE REVIEW

**Comment by tardyp** [comment]
ping?

**Comment by tedder** [comment]
ping. Want to update this and provide a test?

**Comment by tardyp** [comment]
Well, as this does not include new feature, it is just a refacto, I figure it does not need new test.
hyper_sh is closed so the downstream do not need it anymore, though.

**Comment by tedder** [comment]
You're right, existing tests should be fine. But nobody needs this anymore?

**Pull request closed without merging**
